"""
groq_client.py

Acts as the client for interacting with the Groq provider API.
80% of the code was generated by AI. The rest was manually written or edited.
"""

import os
import httpx
from fastapi import HTTPException
import logging

logger = logging.getLogger(__name__)


class GroqClient:
    def __init__(
        self, base_url: str | None = None, client: httpx.AsyncClient | None = None
    ):
        # Support both old and new environment variable names
        self.base_url = base_url or os.getenv(
            "GROQ_API_URL", os.getenv("GROQ_PROVIDER_URL", "http://groq_provider:8003")
        )

        # Determine if we should verify SSL certificates
        environment = os.getenv("ENVIRONMENT", "development").lower()
        verify_ssl = environment in ["production", "prod", "staging"]

        if not verify_ssl:
            logger.warning("SSL verification disabled for Groq client in development")

        # Inject client for testability, otherwise create a new one
        self._client = client or httpx.AsyncClient(verify=verify_ssl)

    async def extract_tokens(self, user_input: str) -> dict:
        return await self._request(
            "GET",
            "/get_tokens",
            params={"user_input": user_input},
        )

    async def get_summary(self) -> dict:
        return await self._request("GET", "/get_summary")

    async def _request(self, method: str, path: str, **kwargs) -> dict:
        try:
            resp = await self._client.request(
                method, f"{self.base_url}{path}", **kwargs
            )
            resp.raise_for_status()
            return resp.json()
        except httpx.RequestError as e:
            raise HTTPException(
                status_code=502, detail=f"Groq provider unavailable: {e}"
            )
        except httpx.HTTPStatusError as e:
            raise HTTPException(
                status_code=e.response.status_code, detail=e.response.text
            )
