"""Client for interacting with the Groq provider API.

80% of the code was generated by AI. The rest was manually written or edited.
"""

import os
import httpx
from fastapi import HTTPException
from pydantic import BaseModel, Field, field_validator
from typing import List
import logging

logger = logging.getLogger(__name__)


class UserPreferences(BaseModel):
    """User music preferences model for AI recommendations."""

    genres: List[str] = Field(
        default_factory=list, description="Preferred music genres"
    )
    artists: List[str] = Field(default_factory=list, description="Preferred artists")
    locations: List[str] = Field(
        default_factory=list, description="Preferred locations"
    )

    @field_validator("genres", "artists", "locations", mode="before")
    @classmethod
    def _normalize_list(cls, v):
        if v is None:
            return []
        if isinstance(v, list):
            return [str(x) for x in v if x is not None]
        return [str(v)]


class GroqClient:
    """HTTP client for Groq AI service communication."""

    def __init__(
        self, base_url: str | None = None, client: httpx.AsyncClient | None = None
    ):
        """Initialize the Groq client with optional base URL and HTTP client."""
        # Support both old and new environment variable names
        self.base_url = base_url or os.getenv(
            "GROQ_API_URL", os.getenv("GROQ_API_URL", "http://groq_provider:8003")
        )

        # Determine if we should verify SSL certificates
        # In development with self-signed certs, we disable verification
        # Left ability in place for future use if when microservices run
        # under different networks/Docker environments
        verify_ssl = False

        if not verify_ssl:
            logger.warning("SSL verification disabled for Groq client in development")

        # Inject client for testability, otherwise create a new one
        self._client = client or httpx.AsyncClient(verify=verify_ssl)

    async def extract_tokens(self, user_input: str) -> dict:
        """Extract location, dates, and artist tokens from user input."""
        logging.info(f"extract_tokens called with user_input: {user_input}")
        return await self._request(
            "GET",
            "/tokens",
            params={"user_input": user_input},
        )

    async def get_user_preferences(self, user_input: str) -> dict:
        """Extract user music preferences from natural language input."""
        return await self._request(
            "GET",
            "/preferences",
            params={"user_input": user_input},
        )

    async def create_recommendations(
        self, user_preferences: UserPreferences | dict, events: list
    ) -> dict:
        """Forward preferences and events to Groq service for recommendations.

        Expected response format:
        {"recommendations": [{"rank": int, "event_id": str, "reason": str}, ...]}
        """
        # Ensure user_preferences is a UserPreferences object
        if isinstance(user_preferences, dict):
            user_preferences = UserPreferences(**user_preferences)

        payload = {
            "user_preferences": user_preferences.model_dump(),
            "events": events,
        }

        return await self._request(
            "POST",
            "/recommendations",
            json=payload,
        )

    async def get_summary(self) -> dict:
        """Get AI-generated summary (placeholder method)."""
        return await self._request("GET", "/summary")

    async def _request(self, method: str, path: str, **kwargs) -> dict:
        try:
            resp = await self._client.request(
                method, f"{self.base_url}{path}", **kwargs
            )
            resp.raise_for_status()
            return resp.json()
        except httpx.RequestError as e:
            raise HTTPException(
                status_code=502, detail=f"Groq provider unavailable: {e}"
            )
        except httpx.HTTPStatusError as e:
            raise HTTPException(
                status_code=e.response.status_code, detail=e.response.text
            )
