"""
groq_service.py

Acts as the main entry point for Groq provider.
80% of the code was generated by AI. The rest was manually written or edited.
"""

import os
from typing import Optional

import uvicorn
from fastapi import FastAPI, HTTPException, APIRouter, Query
from pydantic import BaseModel, ValidationError, Field
from groq import Groq
from starlette.concurrency import run_in_threadpool
from typing import List

import logging
import json

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger(__name__)


class ConcertExtraction(BaseModel):
    location: str
    start_date: str
    end_date: str
    artist: str


class TokenResponse(BaseModel):
    location: str
    start_date: str
    end_date: str
    artist: str


class SummaryResponse(BaseModel):
    summary: str
    model: str
    prompt_tokens: Optional[int] = None
    completion_tokens: Optional[int] = None
    total_tokens: Optional[int] = None


class UserPreferences(BaseModel):
    genres: List[str] = Field(default_factory=list, description="Preferred music genres")
    artists: List[str] = Field(default_factory=list, description="Preferred artists")


class UserPreferencesResponse(BaseModel):
    genres: List[str] = Field(default_factory=list, description="Preferred music genres")
    artists: List[str] = Field(default_factory=list, description="Preferred artists")
    locations: List[str] = Field(default_factory=list, description="Preferred cities")


class Recommendation(BaseModel):
    rank: int = Field(..., description="Ranking of this recommendation in the list")
    event_id: str = Field(..., description="Unique identifier for the recommended event")
    reason: str = Field(..., description="Explanation of why this event is recommended")


class RecommendationsResponse(BaseModel):
    recommendations: List[Recommendation]


class GroqService:
    def __init__(self) -> None:
        self.router = APIRouter()
        self.client: Optional[Groq] = None

        # Routes
        self.router.add_api_route(
            "/",
            self.root,
            methods=["GET"],
        )
        self.router.add_api_route(
            "/get_tokens",
            self.get_tokens,
            methods=["GET"],
            response_model=TokenResponse,
        )
        self.router.add_api_route(
            "/get_summary",
            self.get_summary,
            methods=["GET"],
            response_model=SummaryResponse,
        )
        self.router.add_api_route(
            "/get_user_preferences",
            self.get_user_preferences,
            methods=["GET"],
            response_model=UserPreferences
        )
        self.router.add_api_route(
            "/create_recommendations",
            self.create_recommendations,
            methods=["POST"],
            response_model=RecommendationsResponse
        )

    async def root(self):
        """Health check endpoint."""
        return {"status": "ok", "message": "Groq service is running."}

    async def get_tokens(self, user_input: str = Query(...)) -> TokenResponse:
        """
        Extract tokens (location, dates, artist) from user input about a music event.
        """
        logger.info("Received token count request")
        client = self._ensure_client()

        chat_completion = await run_in_threadpool(
            client.chat.completions.create,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are an extractor.\n"
                        "Fields:\n"
                        "- location\n"
                        "- start_date\n"
                        "- end_date\n"
                        "- artist\n\n"
                        "Rules:\n"
                        "- Dates: ddMMyyyy (e.g., 05082025).\n"
                        "- One date → same start/end.\n"
                        "- Date range → set both.\n"
                        "- Week → Mon as start, Sun as end.\n"
                        "  Examples: 'week 42 of 2025', 'week of 12 May 2026'.\n"
                        "- Month+year → first to last day.\n"
                        "- Year only → 0101YYYY to 3112YYYY.\n"
                        '- Missing/unclear → "unknown".\n'
                        "- No extra details allowed.\n\n"
                        "Output:\n"
                        "- Exactly one JSON line.\n"
                        "- Only the tokens, nothing else.\n"
                        '{"location":"...","start_date":"...",\n'
                        '"end_date":"...","artist":"..."}'
                    ),
                },
                {"role": "user", "content": user_input},
            ],
            model="groq/compound",
            temperature=0.0,
        )

        content = chat_completion.choices[0].message.content.strip()
        logger.debug(f"Model raw output: {content}")

        try:
            data = ConcertExtraction.model_validate_json(content)
            return TokenResponse(**data.model_dump())
        except ValidationError:
            logger.warning("Schema validation failed for model output: %s", content)
            return TokenResponse(
                location="unknown",
                start_date="unknown",
                end_date="unknown",
                artist="unknown",
            )

    async def get_summary(self) -> SummaryResponse:
        """
        Summarization endpoint (stub).
        """
        # client = self._ensure_client()
        # TODO: Implement summarization
        raise HTTPException(status_code=501, detail="Not implemented yet")

    async def get_user_preferences(self, user_input: str = Query(...)) -> UserPreferencesResponse:
        logger.info("Received user preferences request")
        client = self._ensure_client()

        chat_completion = await run_in_threadpool(
            client.chat.completions.create,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are an intent-to-preferences extractor.\n"
                        "Fields:\n"
                        "- genres: array of strings\n"
                        "- artists: array of strings\n"
                        "- locations: array of strings\n"
                        "Rules:\n"
                        "- Extract genres if mentioned (e.g., 'metal', 'rock').\n"
                        "- Extract artists if mentioned (one or more).\n"
                        "- Extract locations if mentioned (one or more).\n"
                        "- Missing/unclear -> empty array or null.\n\n"
                        "Output:\n"
                        "- Exactly one JSON line.\n"
                        "- Only the preferences object, nothing else.\n"
                        '{"genres":["..."],"artists":["..."],"locations":["..."]}'
                    ),
                },
                {"role": "user", "content": user_input},
            ],
            model="groq/compound",
            temperature=0.0,
        )

        content = chat_completion.choices[0].message.content.strip()
        logger.debug(f"Model raw output: {content}")

        try:
            data = UserPreferences.model_validate_json(content)
            return UserPreferencesResponse(**data.model_dump())
        except ValidationError:
            logger.warning("Schema validation failed for user preferences output: %s", content)
            return UserPreferencesResponse(
                genres=[],
                artists=[],
                locations=[]
            )

    async def create_recommendations(self, user_preferences: UserPreferences, events: list) -> RecommendationsResponse:
        """
        Receive user_preferences and events from search_results and create list of recommended events
        """
        logger.info("Received recommendations request")
        client = self._ensure_client()

        # Build prompt messages
        payload = {
            "user_preferences": user_preferences.model_dump(),
            "events": [e.model_dump() for e in events]
        }
        chat_completion = await run_in_threadpool(
            client.chat.completions.create,
            messages=[
                {
                "role": "system",
                "content": (
                    "You are a concert recommendation engine. "
                    "Given user_preferences and a list of candidate events, return the top 3 recommendations. "
                    "Output should be JSON in the format: "
                    "[ { \"rank\": int, \"event_id\": str, \"reason\": str }, … ]"
                )
            },
            {
                "role": "user",
                "content": json.dumps(payload)
            }
            ],
            model="groq/compound",
            temperature=0.0,
        )
        
        content = chat_completion.choices[0].message.content.strip()
        logger.debug("Groq recommendation raw output: %s", content)

        try:
            resp = RecommendationsResponse.model_validate_json(content)
            return resp
        except ValidationError as e:
            logger.warning("Invalid recommendation JSON: %s", content, e)
            return RecommendationsResponse(recommendations = [])

    def _ensure_client(self) -> Groq:
        """
        Lazily initialize Groq client with API key.
        """
        if self.client is not None:
            return self.client

        api_key = os.getenv("GROQ_API_KEY")
        if not api_key:
            logger.error("GROQ_API_KEY not set in environment.")
            raise HTTPException(
                status_code=500, detail="GROQ_API_KEY is not configured"
            )

        self.client = Groq(api_key=api_key)
        return self.client


def create_app() -> FastAPI:
    """Factory to build the FastAPI app with GroqService routes."""
    app = FastAPI(title="Groq Provider", version="1.0.0")
    groq_service = GroqService()
    app.include_router(groq_service.router)
    return app


app = create_app()


# ---------- Entrypoint ----------
def main():
    """Entry point for running the Groq service directly."""
    host = os.getenv("GROQ_HOST", "127.0.0.1")
    port = int(os.getenv("GROQ_PORT", "8003"))
    reload_enabled = os.getenv("GROQ_RELOAD", "false").lower() in ("1", "true", "yes")

    # Check if binding to all interfaces was explicitly allowed
    allow_all = os.getenv("GROQ_ALLOW_BIND_ALL", "false").lower() in (
        "1",
        "true",
        "yes",
    )
    if not allow_all and host in ("0.0.0.0", "::"):  # nosec B104
        logger.warning(
            "Binding to '%s' (all interfaces) is disabled by default. "
            "Override by setting GROQ_ALLOW_BIND_ALL=true. "
            "Falling back to localhost (127.0.0.1).",
            host,
        )
        host = "127.0.0.1"

    uvicorn.run(
        "groq_service:create_app",
        host=host,
        port=port,
        reload=reload_enabled,
        factory=True,
    )


if __name__ == "__main__":
    main()
