"""
groq_service.py

Acts as the main entry point for Groq provider.
80% of the code was generated by AI. The rest was manually written or edited.
"""

import os
from typing import Optional
from datetime import date

import uvicorn
from fastapi import FastAPI, HTTPException, APIRouter, Query
from pydantic import BaseModel, ValidationError, Field, field_validator
from groq import Groq
from starlette.concurrency import run_in_threadpool
from typing import List

import logging
import json

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger(__name__)


class ConcertExtraction(BaseModel):
    locations: List[str]
    start_date: str
    end_date: str
    artists: List[str]


class TokenResponse(BaseModel):
    locations: List[str]
    start_date: str
    end_date: str
    artists: List[str]


class SummaryResponse(BaseModel):
    summary: str
    model: str
    prompt_tokens: Optional[int] = None
    completion_tokens: Optional[int] = None
    total_tokens: Optional[int] = None


class UserPreferences(BaseModel):
    genres: List[str] = Field(
        default_factory=list, description="Preferred music genres"
    )
    artists: List[str] = Field(default_factory=list, description="Preferred artists")
    locations: List[str] = Field(
        default_factory=list, description="Preferred locations"
    )

    @field_validator("genres", "artists", "locations", mode="before")
    @classmethod
    def _normalize_list(cls, v):
        if v is None:
            return []
        if isinstance(v, list):
            return [str(x) for x in v if x is not None]
        return [str(v)]


class UserPreferencesResponse(BaseModel):
    genres: List[str] = Field(
        default_factory=list, description="Preferred music genres"
    )
    artists: List[str] = Field(default_factory=list, description="Preferred artists")
    locations: List[str] = Field(
        default_factory=list, description="Preferred locations"
    )

    @field_validator("genres", "artists", "locations", mode="before")
    @classmethod
    def _normalize_list(cls, v):
        if v is None:
            return []
        if isinstance(v, list):
            return [str(x) for x in v if x is not None]
        return [str(v)]


class Recommendation(BaseModel):
    rank: int = Field(..., description="Ranking of this recommendation in the list")
    event_id: str = Field(
        ..., description="Unique identifier for the recommended event"
    )
    reason: str = Field(..., description="Explanation of why this event is recommended")


class RecommendationsResponse(BaseModel):
    recommendations: List[Recommendation]


class RecommendationsRequest(BaseModel):
    user_preferences: UserPreferences
    events: List[dict]


class GroqService:
    def __init__(self) -> None:
        self.router = APIRouter()
        self.client: Optional[Groq] = None

        # Routes
        self.router.add_api_route(
            "/",
            self.root,
            methods=["GET"],
        )
        self.router.add_api_route(
            "/tokens",
            self.tokens,
            methods=["GET"],
            response_model=TokenResponse,
        )
        self.router.add_api_route(
            "/summary",
            self.summary,
            methods=["GET"],
            response_model=SummaryResponse,
        )
        self.router.add_api_route(
            "/preferences",
            self.preferences,
            methods=["GET"],
            response_model=UserPreferencesResponse,
        )
        self.router.add_api_route(
            "/recommendations",
            self.recommendations,
            methods=["POST"],
            response_model=RecommendationsResponse,
        )

    async def root(self):
        """Health check endpoint."""
        return {"status": "ok", "message": "Groq service is running."}

    async def tokens(self, user_input: str = Query(...)) -> TokenResponse:
        """
        Extract tokens (location, dates, artist) from user input about a music event.
        """
        logger.info("Received token split request")
        client = self._ensure_client()

        chat_completion = await run_in_threadpool(
            client.chat.completions.create,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are an extractor.\n"
                        f"Today is {date.today().strftime('%d%m%Y')} (America/New_York).\n"
                        "Fields:\n"
                        "- locations: array of strings\n"
                        "- start_date: string\n"
                        "- end_date: string\n"
                        "- artists: array of strings\n"
                        "\n"
                        "Rules:\n"
                        "- Dates use ddMMyyyy.\n"
                        "- One date → same start_date and end_date.\n"
                        "- Date range → set both explicitly.\n"
                        "- Week → Mon start, Sun end.\n"
                        "- Month+year → first to last day.\n"
                        "- Year only → 0101YYYY to 3112YYYY.\n"
                        "- If missing/unclear → \"unknown\".\n"
                        "- All dates must be in the future. Never in the past.\n"
                        "- start_date must be in the future. Never in the past.\n"
                        "- end_date must be in the future. Never in the past.\n"
                        "- Month with no year → next such month on/after today.\n"
                        "- Season with no year → this season if ongoing, else next.\n"
                        "- Vague periods (e.g., 'this summer', 'in July') assume "
                        "  NEXT occurrence. Meaning in the FUTURE.\n"
                        "- If a period began and is ongoing → start_date = today.\n"
                        "- Respond with valid JSON only. No extra text.\n"
                        "\n"
                        "Output:\n"
                        "One JSON object exactly:\n"
                        "{\"locations\":[\"...\"],"
                        "\"start_date\":\"...\","
                        "\"end_date\":\"...\","
                        "\"artists\":[\"...\"]}"
                    ),
                },
                {"role": "user", "content": user_input},
            ],
            model="openai/gpt-oss-120b",
            temperature=0.0,
        )

        content = chat_completion.choices[0].message.content.strip()
        logger.debug(f"Model raw output: {content}")

        try:
            data = ConcertExtraction.model_validate_json(content)
            return TokenResponse(**data.model_dump())
        except ValidationError:
            logger.warning("Schema validation failed for model output: %s", content)
            return TokenResponse(
                location="unknown",
                start_date="unknown",
                end_date="unknown",
                artist="unknown",
            )

    async def summary(self) -> SummaryResponse:
        """
        Summarization endpoint (stub).
        """
        # client = self._ensure_client()
        # TODO: Implement summarization
        raise HTTPException(status_code=501, detail="Not implemented yet")

    async def preferences(
        self, user_input: str = Query(...)
    ) -> UserPreferencesResponse:
        logger.info("Received user preferences request")
        client = self._ensure_client()

        chat_completion = await run_in_threadpool(
            client.chat.completions.create,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are an intent-to-preferences extractor.\n"
                        "Your task is to analyze the user's input and"
                        "extract their music preferences.\n"
                        "Output a JSON object with three fields:"
                        "genres, artists, and locations.\n"
                        "You should infer genres from"
                        "mentioned artists when possible.\n"
                        "You can add genres that are commonly"
                        "associated with the identified artists.\n"
                        "If locations are not explicitly mentioned,"
                        "you may suggest locations where "
                        "concerts featuring the identified artists "
                        "are commonly held. Or locations where\n"
                        "artists will be playing in the next year.\n"
                        "If no preferences can be determined, "
                        "return empty arrays for each field.\n"
                        "Extract user preferences into JSON "
                        "with the following fields:\n"
                        "  - genres: array of strings\n"
                        "  - artists: array of strings\n"
                        "  - locations: array of strings\n"
                        "Rules:\n"
                        "- If a field is missing or unclear, return an empty array.\n"
                        "- Output must be a single valid JSON object only.\n"
                        "- Do not include any explanations, text, "
                        "or formatting outside of the JSON.\n"
                        "Format strictly as:\n"
                        '{"genres":["..."],"artists":["..."],"locations":["..."]}'
                    ),
                },
                {"role": "user", "content": user_input},
            ],
            model="moonshotai/kimi-k2-instruct-0905",
            temperature=0.5,
        )

        content = chat_completion.choices[0].message.content.strip()
        logger.debug(f"Model raw output: {content}")

        try:
            data = UserPreferencesResponse.model_validate_json(content, strict=False)
            return data
        except ValidationError:
            logger.warning(
                "Schema validation failed for user preferences output: %s", content
            )
            return UserPreferencesResponse(genres=[], artists=[], locations=[])

    async def recommendations(
        self, payload: RecommendationsRequest
    ) -> RecommendationsResponse:
        """
        Receive userpreferences and events encapsulated in payload,
        compose list of recommended events
        """
        logger.info("Received recommendations request")
        client = self._ensure_client()

        payload_dict = payload.model_dump()
        chat_completion = await run_in_threadpool(
            client.chat.completions.create,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a concert recommendation engine. "
                        "Given 'user_preferences' and a list of 'candidate_events', "
                        "you must return the top 3 recommended events. "
                        "If there are 3 or fewer candidate events, return all of them. "
                        "Do NOT omit any valid event."
                        "Always return at least one recommendation.\n"
                        "Respond **only with valid JSON**, "
                        "no explanations or extra text. "
                        "Do not include markdown, code fences, or commentary.\n"
                        "The JSON must have this exact structure:\n"
                        '{"recommendations":['
                        '{"rank":1,"event_id":"...","reason":"..."},'
                        '{"rank":2,"event_id":"...","reason":"..."},'
                        '{"rank":3,"event_id":"...","reason":"..."}]}\n'
                        "If there are fewer than 3 events, "
                        "include only as many as exist. "
                        "Omit higher ranks instead of leaving them empty. "
                        "Never return an empty list for 'recommendations'."
                    ),
                },
                {"role": "user", "content": json.dumps(payload_dict)},
            ],
            model="moonshotai/kimi-k2-instruct-0905",
            temperature=0.0,
            response_format={"type": "json_object"},
        )

        content = chat_completion.choices[0].message.content.strip()
        logger.info("Groq recommendation raw output: %s", content)

        try:
            return RecommendationsResponse.model_validate_json(content)
        except ValidationError as e:
            logger.warning("Invalid recommendation JSON: %s; error: %s", content, e)
            return RecommendationsResponse(recommendations=[])

    def _ensure_client(self) -> Groq:
        """
        Lazily create and return the Groq client using GROQ_API_KEY.
        """
        if self.client is None:
            api_key = os.getenv("GROQ_API_KEY")
            if not api_key:
                logger.error("GROQ_API_KEY is not set")
                raise HTTPException(
                    status_code=500, detail="GROQ_API_KEY is not configured"
                )
            self.client = Groq(api_key=api_key)
        return self.client


# ---------- ASGI app factory ----------
def create_app() -> FastAPI:
    app = FastAPI(title="Groq Provider", version="0.1.0")
    service = GroqService()
    app.include_router(service.router)
    return app


# Expose module-level ASGI app for uvicorn (module:app)
app = create_app()

if __name__ == "__main__":
    # Run directly: python groq_service.py
    uvicorn.run(app, host="127.0.0.1", port=int(os.getenv("PORT", "8000")))
