services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: concert_backend
    ports:
      - "8000:8000"
    depends_on:
      - ticketmaster_provider
      - jambase_provider
    environment:
      TICKETMASTER_API_URL: http://ticketmaster_provider:8001
      JAMBASE_API_URL: http://jambase_provider:8002
    env_file:
      - backend/.env

  ticketmaster_provider:
    build:
      context: .
      dockerfile: providers/ticketmaster/Dockerfile
    container_name: ticketmaster_provider
    ports:
      - "8001:8001"

  jambase_provider:
    build:
      context: .
      dockerfile: providers/jambase/Dockerfile
    container_name: jambase_provider
    ports:
      - "8002:8002"
    environment:
      JAMBASE_API_KEY: ${JAMBASE_API_KEY} 

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: beatmap_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
